export const comments = [
    "I've got that summertime sadness. ☀️",
    "Born to die. 💔",
    "Forever young and beautiful. 🌹",
    "Blue jeans forever. 👖",
    "Playing video games. 🎮",
    "I will love you till the end of time. ⏳",
    "West Coast vibes. 🌊",
    "Cinnamon girl in a cinnamon world. 🌟",
    "Ride on. 🏍️",
    "Feeling high by the beach. 🏖️",
    "A lust for life. ❤️",
    "Doin' time under the sun. 🌞",
    "Norman freaking Rockwell. 🎨",
    "Lost in a dark paradise. 🌌",
    "Shades of cool. 😎",
    "Brooklyn baby on the scene. 🗽",
    "All you need is love. 💕",
    "Ultraviolence in the air. 🔥",
    "Off to the races we go. 🏇",
    "Hope is a dangerous thing. ⚠️",
    "Born to run wild. 🏃‍♂️",
    "God knows I tried. 🙏",
    "Riding in a white Mustang. 🚗",
    "Sweet cherry pie. 🍒",
    "Happiness is a butterfly. 🦋",
    "You're the greatest. ⭐",
    "Once upon a dream. 🌙",
    "Let me love you like a woman. 🌹",
    "Chemtrails over the country club. ☁️",
    "Freak out. 🤪",
    "Light my fire. 🔥",
    "Break on through to the other side. 🚪",
    "Riders on the storm. 🌧️",
    "People are strange. 👽",
    "This is the end. 🕰️",
    "L.A. Woman in the city. 🌆",
    "Hello, I love you. 👋❤️",
    "Touch me. 🤝",
    "Love her madly. 💖",
    "Roadhouse blues. 🎸",
    "Can't get no satisfaction. 😤",
    "Paint it black. 🎨",
    "Sympathy for the devil. 😈",
    "You can't always get what you want. 🥺",
    "Gimme shelter. 🏠",
    "Start me up. 🚀",
    "Brown sugar in the air. 🍬",
    "Wild horses couldn't drag me away. 🐴",
    "Jumpin' Jack Flash on the move. ⚡",
    "Angie, oh Angie. 🎶",
    "The times they are a-changin'. ⏳",
    "Like a rolling stone. 🔄",
    "Blowin' in the wind. 🍃",
    "Tangled up in blue. 🔵",
    "Hey Mr. Tambourine Man. 🥁",
    "All along the watchtower. 🏰",
    "Knockin' on heaven's door. 🚪",
    "Just like a woman. 👩",
    "Subterranean homesick blues. 🏠",
    "It ain't me, babe. 🚫",
    "Sultans of swing. 🎸",
    "Money for nothing. 💰",
    "Tunnel of love. ❤️",
    "Romeo and Juliet's tale. 📜",
    "Walk of life. 🚶",
    "So far away. 🌌",
    "Brothers in arms. 🤝",
    "Your latest trick. 🎩",
    "Why worry? 🤷",
    "Ride across the river. 🛶",
    "London calling out. 📞",
    "Should I stay or should I go? 🤔",
    "Rock the casbah. 🕌",
    "I fought the law. ⚖️",
    "Train in vain. 🚂",
    "Clampdown in effect. 🚨",
    "White riot on the rise. ⚪",
    "Lost in the supermarket. 🛒",
    "Rudie can't fail. 🎶",
    "The guns of Brixton. 🔫",
    "Skinny love. 💔",
    "Holocene days. 🌍",
    "Blood bank memories. 🩸",
    "For Emma, forever ago. 🌠",
    "Re: Stacks of emotion. 📚",
    "33 'God'. ✨",
    "Towers of sound. 🏯",
    "Flume of dreams. 🌊",
    "Hey, Ma. 👋",
    "Calgary nights. 🌌",
    "Sweet Jane's tune. 🎶",
    "Heroin in the veins. 💉",
    "Pale blue eyes. 👀",
    "I'm waiting for the man. ⏳",
    "Sunday morning vibes. ☀️",
    "Venus in furs. 🪐",
    "Rock & roll heart. 🎸",
    "All tomorrow's parties. 🎉",
    "White light/white heat. 💡",
    "Femme fatale. 👠",
    "I wanna be adored. 🌟",
    "She bangs the drums. 🥁",
    "Waterfall of sound. 💧",
    "Made of stone. 🗿",
    "Fools gold. 💰",
    "I am the resurrection. ✨",
    "Sally Cinnamon's tune. 🍬",
    "Ten storey love song. 🏢",
    "Love spreads wide. 🌈",
    "Elephant stone in the garden. 🐘",
    "Go your own way. 🛤️",
    "Dreams in the night. 🌌",
    "Landslide of emotions. ⛰️",
    "Rhiannon rings like a bell. 🔔",
    "The chain can't hold us. ⛓️",
    "Don't stop believing. 🚫",
    "Everywhere you go. 🌎",
    "Little lies, big truths. 🤥",
    "Gypsy heart. 🔮",
    "Tusk to tusk. 🐘"
  ];